### ISSUE TITLE
Update init.php

### ISSUE THREAD

**Issue by Dunkstormen** [christran/PHP-OOP-Login-Register-System#11]
Due to that all class files uses lowercase and the classes themselves is with the first letter being uppercase, you will get a "No such file" error.

On line 26 in init.php replace the following:
`require_once 'classes/' . $class . '.php';`

With the following:
`require_once 'classes/' . strtolower($class) . '.php';`

**Comment by tomcatbuzz** [comment]
I never received any errors. A "No such file" error is most likely a typo in your code or file naming method. If you have a page including or redirecting to another page and you didn't change the name, you will get that error.  You should research and learn PHP naming conventions. Class names start with a Capital letter.
https://pear.php.net/manual/en/standards.naming.php
https://www.codeigniter.com/user_guide/general/styleguide.html#file-naming

**Comment by Dunkstormen** [comment]
@tomcatbuzz If you look in his repo, all his files are spelled with all letters being lowercase. But when he is defining the class he writes the first letter uppercase like `class Config {}` which makes **spl_autoload_register** calling for a file with the starting letter being uppercase like **"Config.php"** and not **"config.php"** which is what he have called his file.

**Comment by tomcatbuzz** [comment]
I understand what you are saying. But the solution is to go back to the Class files and change them from config.php to Config. php. PHP naming convention states that all Classes start with a Capital letter, which is what the code shows. Your code is setting all ($class) to lower case (strttolower) changes the ($class) code to all lower case, inviting more errors. Class name and file name has to match I agree or you get the no such file error.  But in the working code of PHP the Class Name has to be a capital letter. Did you get the program to work by using your code change?

**Comment by Dunkstormen** [comment]
Well to some state yes, but some of the method was creating fatal errors...

**Comment by tomcatbuzz** [comment]
@Dunkstormen were you running that on a local server or web server. I think others get that type of error trying to run the package from their web server. And this issue is most likely what you said before, with the letter capitalization. The package owner did that on his own, but the original code developer (from a tutorial @codesource) showed it the correct way. You should try to re-open and fix that. But, I would go through the whole package and re-name all the file names that need to be upper or lower case.
